commit 00
2022-d04-java-fs/gestion-des-transports-front pull request #32
Opened 2022-07-05 12:07 UTC by EtienneRenoton

2022-07-07 12:15 UTC, Axurynn requested changes

2022-07-07 12:15 UTC, Axurynn commented on src/app/menu-component/menu-component.component.html
> +  </button>
Le bouton est complètement collé à droite de la fenêtre. Je pense qu'il serait mieux un peu décalé (même marge qu'entre la page et le logo pour équilibrer la navbar ?)

2022-07-07 12:15 UTC, Axurynn commented on src/app/menu-component/menu-component.component.html
> +  <a class="navbar-brand" href="#"><img src="https://media.discordapp.net/attachments/988404259794079787/993870589276196954/GDT_Logo.png" class="Image"></a>
Habituellement, on utilise le camelCase pour les noms de classe, du coup "Image" serait plutôt "image" :-) et j'aurais même été plus explicite dans le nom de la classe en mettant un nom détaillé comme "logoNavBar" (je suppose qu'on aura sans doute d'autres images dans l'app)

2022-07-07 12:15 UTC, Axurynn commented on src/app/menu-component/menu-component.component.scss
> +.Image {
Idem que pour le fichier html 
=> Habituellement, on utilise le camelCase pour les noms de classe, du coup ".Image" serait plutôt ".image" (ou si tu suis la suite de mon commentaire ".logoNavBar") :-)

2022-07-07 12:15 UTC, Axurynn commented on src/app/menu-component/menu-component.component.scss
> +  width: 80px;
à voir avec les autres mais je le trouve un poil gros ce logo :-) et peut être le passer en svg ?

2022-07-07 12:15 UTC, Axurynn commented on src/app/menu-component/menu-component.component.spec.ts
> +});
ça c'est le test de base des composants, qui passera à coup sur... Mais du coup ton code n'est pas testé. Je pense qu'il aurait fallu le tester comme Christophe nous l'avait montré vendredi (01/07/2022 > par exemple, fichier test.component.spec.ts du projet digiD04routestests)

2022-07-07 12:19 UTC, Axurynn requested changes
L'architecture proposée ensemble hier soir n'est pas respectée. 
![image](https://user-images.githubusercontent.com/79093561/177771373-f34bebb7-f504-4fec-a8b9-81b14c1bcf52.png)

2022-07-07 12:36 UTC, EtienneRenoton commented on src/app/menu-component/menu-component.component.scss
> +.Image {
de même

2022-07-11 08:09 UTC, JeremyPayet requested changes
J'ai remarqué que le fichier [src/app/app-routing.module.ts](https://github.com/2022-d04-java-fs/gestion-des-transports-front/blob/USGDT003-EtienneRenoton/src/app/app-routing.module.ts) n'avait pas les routes définies dans la constante routes. 
Il serait judicieux de les définir, même si tu fais une redirection vers la page de base

2022-07-11 09:01 UTC, EtienneRenoton commented on src/app/app.component.html
> +<app-menu-component></app-menu-component>
Par rapport à tes deux remarques : 
J'ai pull ma propre branch lors de la création de mon deuxième issue. On a vu avec Marion que toutes les modifications du menu seront faites et push sur l'issue 009. 
J'ai pris en compte la remarque du router-oulet et l'est integré dans l'issue 009

2022-07-11 12:01 UTC, closed without merging