USGDT004-JeremyPayet
2022-d04-java-fs/gestion-des-transports-front pull request #33
Opened 2022-07-05 12:09 UTC by JeremyPayet

2022-07-06 12:45 UTC, EmileDebris requested changes

2022-07-06 12:45 UTC, EmileDebris commented on src/app/components/list-reservation/list-reservation.component.ts
> +      date: "22/06/2017 12:30",
Les dates sont stockés au format Date (contient la date et l'heure) pour pouvoir les manipuler.
Tu peux gérer l'affichage dans la page avec le pipe date

2022-07-06 12:45 UTC, EmileDebris commented on src/app/components/list-reservation/list-reservation.component.ts
> +
Il serait peut être plus judicieux de n'avoir qu'une liste de réservations pour ne faire qu'une requête au back pour toutes les récupérer (passées et futures) d'un coup, et après de faire le tri dans le front en fonction de la date du jour

2022-07-06 12:45 UTC, EmileDebris commented on src/app/pages/collab/collab.module.ts
> +  ],
On devrait peut être créer un Shared module qui contiendrait tous nos composants, pipes, validators, ... pour pouvoir avoir une structure plus organisée et souple, comme ce qu'on avait en TP :
![image](https://user-images.githubusercontent.com/72602777/177551046-99156f15-d775-4318-ae84-45c934221ad7.png)

Comme ça on centralise les imports de module du type NgdPaginationModule ou ReactiveFormsModule dans le shared.module.ts, et dans nos pages on importe juste CommonModule et SharedModule

2022-07-06 12:45 UTC, EmileDebris commented on src/app/components/list-reservation/list-reservation.component.html
> +  <div class="card-header" (click)="isCollapsed = !isCollapsed" [attr.aria-expanded]="!isCollapsed"
Je sais pas si c'est utile de faire un collapse là dessus, vu que le composant sera tout seul sur la page

2022-07-06 13:10 UTC, Axurynn requested changes

2022-07-06 13:10 UTC, Axurynn commented on src/app/components/list-reservation/list-reservation.component.ts
> +      date: "22/06/2017 12:30",
Le format enregistré en back est le suivant : "2022-07-06T11:22:12" (type LocalDateTime)

2022-07-06 13:10 UTC, Axurynn commented on src/app/components/list-reservation/list-reservation.component.ts
> +  open(content: any, objet: any): void {
content et objet sont de type objet et pas de type any

2022-07-06 13:12 UTC, Axurynn commented on src/app/pages/collab/collab.module.ts
> +  ],
Je suis d'accord avec Emile, centraliser les imports et créer un module Shared permet d'avoir une structure plus organisée.

2022-07-07 08:34 UTC, JeremyPayet commented on src/app/components/list-reservation/list-reservation.component.ts
> +  open(content: any, objet: any): void {
```suggestion
  open(content: object, objet: Reservation): void {
```
content a été passé au type object et objet au type Reservation

2022-07-07 08:35 UTC, JeremyPayet commented on src/app/components/list-reservation/list-reservation.component.ts
> +  open(content: any, objet: any): void {
```suggestion
  open(content: object, objet: Reservation): void {
```
content a été passé au type object et objet au type Reservation

2022-07-07 08:38 UTC, JeremyPayet commented on src/app/components/list-reservation/list-reservation.component.html
> +    <table class="table table-striped">
J'ai ajouté des col-3 pour régler le décalage des colonnes

2022-07-07 10:29 UTC, JeremyPayet commented on src/app/components/list-reservation/list-reservation.component.ts
> +
J'ai créé une fonction findReservations qui se charge d'initialiser reservationList à partir de historyList

2022-07-07 10:29 UTC, JeremyPayet commented on src/app/components/list-reservation/list-reservation.component.ts
> +      date: "22/06/2017 12:30",
Le format a été pris en compte et traité dans le html

2022-07-11 07:49 UTC, EmileDebris requested changes
Ta page ne devrait pas s'appeler Collab, mais un truc du genre "CarpoolReservations", sinon on va avoir des conflits de noms avec le module Collab qui contient les différents composants des pages accessibles par les collaborateurs

2022-07-11 11:54 UTC, EmileDebris approved these changes

2022-07-11 12:34 UTC, Axurynn approved these changes

2022-07-11 12:35 UTC, merged