USGDT009-EtienneRenoton
2022-d04-java-fs/gestion-des-transports-front pull request #34
Opened 2022-07-06 08:42 UTC by EtienneRenoton

2022-07-11 12:15 UTC, EmileDebris requested changes
il faudrait rajouter un service carpool qui fait les requêtes au Back pour alimenter les tableaux avec les vraies données et non des données factice codées dans le front (offer.json)

2022-07-11 12:15 UTC, EmileDebris commented on src/app/collab/collab.module.ts
> +  ],
Tes imports sont un peu bizarres, ça devrait ressemble plus à ça  :

![image](https://user-images.githubusercontent.com/72602777/178260654-e4650914-915f-4e53-8149-3ed7fbca82ba.png)

2022-07-11 12:15 UTC, EmileDebris commented on src/app/app.module.ts
> +
Tes imports sont un peu bizarres, ça devrait ressemble plus à ça dans l'app-module : 
![image](https://user-images.githubusercontent.com/72602777/178261049-d0cd8ae5-ad94-44c9-b163-d32a56b1d16f.png)

2022-07-11 12:15 UTC, EmileDebris commented on src/app/routing/routing.module.ts
> +  ]
Ce routing.module.ts et le dossier qui le contiennent ne devraient pas exister, on a déjà le app-routing.module.ts à la racine de l'application

2022-07-11 12:28 UTC, EtienneRenoton commented on src/app/collab/collab.module.ts
> +  ],
C'est formaté !

2022-07-11 12:28 UTC, EtienneRenoton commented on src/app/app.module.ts
> +
Formaté aussi !

2022-07-11 12:29 UTC, EtienneRenoton commented on src/app/routing/routing.module.ts
> +  ]
C'est supprimé

2022-07-11 12:41 UTC, fhautefeuille reviewed
Il manque un "s" au dossier "services"

2022-07-11 12:47 UTC, Axurynn requested changes

2022-07-11 12:47 UTC, Axurynn commented on src/app/collab/components/offer-list/offer-list.component.html
> +    <table class="table table-striped">
Pourquoi avoir mis un style différents pour "Annonces en cours" et "historique" ? 
![image](https://user-images.githubusercontent.com/79093561/178262979-b658d98e-5b4a-472b-966b-3cdbeda28414.png)

2022-07-11 12:47 UTC, Axurynn commented on src/app/collab/components/offer-list/offer-list.component.html
> +<header></header>
à supprimer

2022-07-11 12:47 UTC, Axurynn commented on src/app/collab/components/offer-list/offer-list.component.html
> +<div class="card-body">
- tu utilises "card-header" et "card-body" mais tu n'as pas englobé le tout dans une <div class="card">... à revoir avec le commentaire plus bas (style différents des deux h4)

- Attention aussi, tu places un h4 après un h2 sans h3 entre les 2. Je comprends que c'était pour le visuel mais les titres ont un impact sur le référencement. Mieux vaut, à mon sens, retravailler le visuel avec les classes bootstrap et respecter l'ordre des titres :-) (cf https://www.webrankinfo.com/dossiers/techniques/balises-h1-h2-h3)

2022-07-11 12:56 UTC, fhautefeuille requested changes
En termes d'organisation, j'ai mis toutes les images du dossier "assets" dans un sous-dossier "images"
Il faudra du coup changer le chemin dans la balise img src du fichier HTML

2022-07-11 12:58 UTC, EtienneRenoton commented on src/app/collab/components/offer-list/offer-list.component.html
> +    <table class="table table-striped">
C'est corrigé

2022-07-11 12:58 UTC, EtienneRenoton commented on src/app/collab/components/offer-list/offer-list.component.html
> +<header></header>
supprimé

2022-07-11 13:01 UTC, EtienneRenoton commented on src/app/collab/components/offer-list/offer-list.component.html
> +<div class="card-body">
J'ai un visuel uniforme en enfermant mes tableaux dans deux card identique et en changeant les titres en h3. Est ce que tu peux me dire si ça te convient sinon ce que tu entends par "retravailler le visuel avec les classes bootstrap"

2022-07-11 13:22 UTC, fhautefeuille commented on src/app/collab/components/offer-list/offer-list.component.html
> +    <table class="table table-striped">
Dans "Annonces en cours", juste mettre "Départ" plutôt que "Lieu de Départ" ?

2022-07-11 13:56 UTC, EtienneRenoton commented on src/assets/offer.json
> +[
J'ai push le carpool service, j'entends que tu me confirme que c'est correct avant de DL le offer.json ?

2022-07-11 14:28 UTC, Axurynn commented on src/app/collab/components/offer-list/offer-list.component.html
> +    <table class="table table-striped">
Dans le template qu'on nous a donné, c'était "Lieu de départ" et "Lieu de destination". Je ne sais pas si ça change quelque chose ? Peu importe

2022-07-11 14:30 UTC, Axurynn commented on src/app/collab/components/offer-list/offer-list.component.html
> +<div class="card-body">
![image](https://user-images.githubusercontent.com/79093561/178287864-116aec47-8a2d-4058-ba30-f7e68200d6a9.png)
Je parlais de la différence entre le "template" et le visuel de l'app (comme on peut le voir sur le screen). "retravailler le visuel avec les classes bootstrap" c'était pour moi changer la taille et le gras de la police par exemple, pour le faire paraitre plus petit que le h3 de base fourni par HTML.

2022-07-11 14:46 UTC, fhautefeuille approved these changes

2022-07-12 08:14 UTC, EmileDebris approved these changes

2022-07-12 08:14 UTC, Axurynn approved these changes

2022-07-12 08:14 UTC, merged